#include "pure_pursuit_controller/pure_pursuit_controller.hpp"

#include <cmath>
#include <memory>
#include <string>

#include "pluginlib/class_list_macros.hpp"

#include "tf2/LinearMath/Matrix3x3.h"
#include "tf2/LinearMath/Quaternion.h"

namespace pure_pursuit_controller
{

// =========================================================
// configure()
// =========================================================
//
// Called by Nav2 Controller Server when the controller plugin
// is created.
//
// This is where we:
//   - store the lifecycle node
//   - store TF buffer
//   - store costmap
//   - read controller parameters
//
// =========================================================

void PurePursuitController::configure(
  const rclcpp_lifecycle::LifecycleNode::WeakPtr & parent,
  std::string name,
  const std::shared_ptr<tf2_ros::Buffer> tf,
  const std::shared_ptr<nav2_costmap_2d::Costmap2DROS> costmap_ros)
{
  node_ = parent;

  plugin_name_ = name;

  tf_ = tf;

  costmap_ros_ = costmap_ros;

  auto node = node_.lock();

  // ---------------------------------------------------------
  // Read controller parameters from Nav2 YAML
  // ---------------------------------------------------------

  linear_velocity_ =
    node->declare_parameter<double>(
      plugin_name_ + ".linear_velocity",
      0.2);

  angular_gain_ =
    node->declare_parameter<double>(
      plugin_name_ + ".angular_gain",
      1.0);

  RCLCPP_INFO(
    node->get_logger(),
    "Pure Pursuit Controller configured");
}


// =========================================================
// cleanup()
// =========================================================
//
// Called when Nav2 unloads / cleans the controller.
//
// =========================================================

void PurePursuitController::cleanup()
{
  global_plan_.poses.clear();

  current_waypoint_index_ = 0;

  RCLCPP_INFO(
    node_.lock()->get_logger(),
    "Pure Pursuit Controller cleaned up");
}


// =========================================================
// activate()
// =========================================================
//
// Called when the Controller Server activates the plugin.
//
// =========================================================

void PurePursuitController::activate()
{
  RCLCPP_INFO(
    node_.lock()->get_logger(),
    "Pure Pursuit Controller activated");
}


// =========================================================
// deactivate()
// =========================================================
//
// Called when the Controller Server deactivates the plugin.
//
// =========================================================

void PurePursuitController::deactivate()
{
  RCLCPP_INFO(
    node_.lock()->get_logger(),
    "Pure Pursuit Controller deactivated");
}


// =========================================================
// setPlan()
// =========================================================
//
// Nav2 Planner Server generates a global path.
//
// That path is passed to our controller through this method.
//
// =========================================================

void PurePursuitController::setPlan(
  const nav_msgs::msg::Path & path)
{
  // Store the path generated by Nav2 Planner
  global_plan_ = path;

  // Start from the first waypoint
  current_waypoint_index_ = 0;

  RCLCPP_INFO(
    node_.lock()->get_logger(),
    "Received path with %zu poses",
    global_plan_.poses.size());
}


// =========================================================
// computeVelocityCommands()
// =========================================================
//
// Main controller logic.
//
// Input:
//   pose     -> current robot pose
//   velocity -> current robot velocity
//   goal_checker
//
// Output:
//   TwistStamped -> velocity command
//
// Logic:
//
//   1. Get current robot pose
//   2. Select current path waypoint
//   3. Transform waypoint into robot pose frame
//   4. Calculate direction to waypoint
//   5. Calculate heading error
//   6. Apply proportional angular control
//   7. Apply constant linear velocity
//
// =========================================================

geometry_msgs::msg::TwistStamped
PurePursuitController::computeVelocityCommands(
  const geometry_msgs::msg::PoseStamped & pose,
  const geometry_msgs::msg::Twist & velocity,
  nav2_core::GoalChecker * goal_checker)
{
  // These inputs are not directly used in this simple controller
  (void)velocity;
  (void)goal_checker;

  geometry_msgs::msg::TwistStamped cmd_vel;

  auto node = node_.lock();

  // ---------------------------------------------------------
  // Command timestamp and frame
  // ---------------------------------------------------------

  cmd_vel.header.stamp = node->now();

  cmd_vel.header.frame_id =
    pose.header.frame_id;


  // =========================================================
  // 1. Check whether a path exists
  // =========================================================

  if (global_plan_.poses.empty()) {

    cmd_vel.twist.linear.x = 0.0;

    cmd_vel.twist.angular.z = 0.0;

    return cmd_vel;
  }


  // =========================================================
  // 2. Check whether all waypoints are completed
  // =========================================================

  if (current_waypoint_index_ >=
      global_plan_.poses.size())
  {
    cmd_vel.twist.linear.x = 0.0;

    cmd_vel.twist.angular.z = 0.0;

    return cmd_vel;
  }


  // =========================================================
  // 3. Get robot position
  // =========================================================

  const double robot_x =
    pose.pose.position.x;

  const double robot_y =
    pose.pose.position.y;


  // =========================================================
  // 4. Convert robot orientation to yaw
  // =========================================================

  tf2::Quaternion q;

  q.setX(
    pose.pose.orientation.x);

  q.setY(
    pose.pose.orientation.y);

  q.setZ(
    pose.pose.orientation.z);

  q.setW(
    pose.pose.orientation.w);


  double roll;
  double pitch;
  double current_yaw;

  tf2::Matrix3x3(q).getRPY(
    roll,
    pitch,
    current_yaw);


  // =========================================================
  // 5. Select current waypoint from global path
  // =========================================================

  geometry_msgs::msg::PoseStamped target =
    global_plan_.poses[
      current_waypoint_index_];


  // =========================================================
  // 6. Transform target into robot pose frame
  // =========================================================
  //
  // Example:
  //
  // Global path frame = map
  // Robot pose frame  = odom
  //
  // We transform:
  //
  // map -> odom
  //
  // so that robot and target are expressed in the same frame.
  //
  // =========================================================

  geometry_msgs::msg::PoseStamped
    target_in_pose_frame;

  try {

    target_in_pose_frame =
      tf_->transform(
        target,
        pose.header.frame_id,
        tf2::durationFromSec(0.1));

  } catch (const tf2::TransformException & ex) {

    RCLCPP_WARN_THROTTLE(
      node->get_logger(),
      *node->get_clock(),
      1000,

      "Failed to transform target from %s to %s: %s",

      target.header.frame_id.c_str(),

      pose.header.frame_id.c_str(),

      ex.what());

    // Stop robot if TF is unavailable

    cmd_vel.twist.linear.x = 0.0;

    cmd_vel.twist.angular.z = 0.0;

    return cmd_vel;
  }


  // =========================================================
  // 7. Get target position
  // =========================================================

  double target_x =
    target_in_pose_frame.pose.position.x;

  double target_y =
    target_in_pose_frame.pose.position.y;


  // Difference between robot and target

  double dx =
    target_x - robot_x;

  double dy =
    target_y - robot_y;


  // Distance to target

  double distance =
    std::sqrt(
      dx * dx +
      dy * dy);


  // =========================================================
  // 8. Check whether current waypoint is reached
  // =========================================================

  if (distance < waypoint_tolerance_) {

    // Move to next waypoint

    current_waypoint_index_++;


    // -------------------------------------------------------
    // Check whether entire path is completed
    // -------------------------------------------------------

    if (current_waypoint_index_ >=
        global_plan_.poses.size())
    {
      cmd_vel.twist.linear.x = 0.0;

      cmd_vel.twist.angular.z = 0.0;

      RCLCPP_INFO(
        node->get_logger(),
        "All waypoints reached");

      return cmd_vel;
    }


    // -------------------------------------------------------
    // Get next waypoint
    // -------------------------------------------------------

    target =
      global_plan_.poses[
        current_waypoint_index_];


    // -------------------------------------------------------
    // Transform next waypoint
    // -------------------------------------------------------

    try {

      target_in_pose_frame =
        tf_->transform(
          target,
          pose.header.frame_id,
          tf2::durationFromSec(0.1));

    } catch (const tf2::TransformException & ex) {

      RCLCPP_WARN(
        node->get_logger(),
        "Failed to transform next waypoint: %s",
        ex.what());

      cmd_vel.twist.linear.x = 0.0;

      cmd_vel.twist.angular.z = 0.0;

      return cmd_vel;
    }


    // Update target position

    target_x =
      target_in_pose_frame.pose.position.x;

    target_y =
      target_in_pose_frame.pose.position.y;


    // Update target difference

    dx =
      target_x - robot_x;

    dy =
      target_y - robot_y;
  }


  // =========================================================
  // 9. Calculate target angle
  // =========================================================

  const double target_angle =
    std::atan2(
      dy,
      dx);


  // =========================================================
  // 10. Calculate heading error
  // =========================================================

  double heading_error =
    target_angle - current_yaw;


  // ---------------------------------------------------------
  // Normalize heading error to [-pi, pi]
  // ---------------------------------------------------------

  heading_error =
    std::atan2(
      std::sin(heading_error),
      std::cos(heading_error));


  // =========================================================
  // 11. Proportional angular control
  // =========================================================
  //
  // angular velocity =
  //     angular_gain × heading error
  //
  // =========================================================

  double angular_velocity =
    angular_gain_ *
    heading_error;


  // ---------------------------------------------------------
  // Limit angular velocity
  // ---------------------------------------------------------

  const double max_angular_velocity =
    1.0;


  if (angular_velocity >
      max_angular_velocity)
  {
    angular_velocity =
      max_angular_velocity;
  }


  if (angular_velocity <
      -max_angular_velocity)
  {
    angular_velocity =
      -max_angular_velocity;
  }


  // =========================================================
  // 12. Constant linear velocity
  // =========================================================

  cmd_vel.twist.linear.x =
    linear_velocity_;


  cmd_vel.twist.angular.z =
    angular_velocity;


  // =========================================================
  // 13. Debug information
  // =========================================================

  RCLCPP_INFO_THROTTLE(
    node->get_logger(),
    *node->get_clock(),
    500,

    "POSE[%s] x=%.2f y=%.2f yaw=%.1f deg | "
    "TARGET[%s] x=%.2f y=%.2f | "
    "target_angle=%.1f deg | "
    "error=%.1f deg | "
    "cmd_linear=%.2f cmd_angular=%.2f",

    pose.header.frame_id.c_str(),

    robot_x,
    robot_y,

    current_yaw * 180.0 / M_PI,

    target_in_pose_frame.header.frame_id.c_str(),

    target_x,
    target_y,

    target_angle * 180.0 / M_PI,

    heading_error * 180.0 / M_PI,

    cmd_vel.twist.linear.x,

    cmd_vel.twist.angular.z);


  return cmd_vel;
}


// =========================================================
// setSpeedLimit()
// =========================================================
//
// Nav2 may call this to change the controller speed.
//
// =========================================================

void PurePursuitController::setSpeedLimit(
  const double & speed_limit,
  const bool & percentage)
{
  if (percentage) {

    linear_velocity_ =
      linear_velocity_ *
      speed_limit /
      100.0;

  } else {

    linear_velocity_ =
      speed_limit;
  }
}

}  // namespace pure_pursuit_controller


// =========================================================
// Pluginlib registration
// =========================================================

PLUGINLIB_EXPORT_CLASS(
  pure_pursuit_controller::PurePursuitController,
  nav2_core::Controller)